name: TestPlugin
version: '1.0'
main: fr.skitroz.testPlugin.Main
api-version: '1.20'
commands:
  scoreboard:
    description: "Commande pour afficher le scoreboard"
    usage: "/scoreboard"
    aliases: [sc]
    permission: "testplugin.scoreboard"
    permission-message: "Vous n'avez pas la permission d'utiliser cette commande"
  permission:
    description: "Commande pour donner la permission"
    usage: "/permission <joueur> <permission>"
    permission: "testplugin.permission"
    permission-message: "Vous n'avez pas la permission d'utiliser cette commande"
  display:
    description: "Commande pour afficher un message"
    usage: "/display [text] [billBoard] [backgroundColor] <[x]> <[y]> <[z]>"
    permission: "testplugin.display"
    permission-message: "Vous n'avez pas la permission d'utiliser cette commande"
  remove-display:
    description: "Commande pour enlever le message"
    usage: "/remove-display"
    aliases: [rd]
    permission: "testplugin.remove-display"
    permission-message: "Vous n'avez pas la permission d'utiliser cette commande"
permissions:
    testplugin.scoreboard:
        description: "Permet d'utiliser la commande /scoreboard"
        default: false